//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandonTempConverterForm.TempConverter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempConverter.ITemperatureConvert")]
    public interface ITemperatureConvert {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperatureConvert/c2f", ReplyAction="http://tempuri.org/ITemperatureConvert/c2fResponse")]
        int c2f(int celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperatureConvert/c2f", ReplyAction="http://tempuri.org/ITemperatureConvert/c2fResponse")]
        System.Threading.Tasks.Task<int> c2fAsync(int celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperatureConvert/f2c", ReplyAction="http://tempuri.org/ITemperatureConvert/f2cResponse")]
        int f2c(int fahreneheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemperatureConvert/f2c", ReplyAction="http://tempuri.org/ITemperatureConvert/f2cResponse")]
        System.Threading.Tasks.Task<int> f2cAsync(int fahreneheit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITemperatureConvertChannel : BrandonTempConverterForm.TempConverter.ITemperatureConvert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemperatureConvertClient : System.ServiceModel.ClientBase<BrandonTempConverterForm.TempConverter.ITemperatureConvert>, BrandonTempConverterForm.TempConverter.ITemperatureConvert {
        
        public TemperatureConvertClient() {
        }
        
        public TemperatureConvertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemperatureConvertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemperatureConvertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemperatureConvertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int c2f(int celsius) {
            return base.Channel.c2f(celsius);
        }
        
        public System.Threading.Tasks.Task<int> c2fAsync(int celsius) {
            return base.Channel.c2fAsync(celsius);
        }
        
        public int f2c(int fahreneheit) {
            return base.Channel.f2c(fahreneheit);
        }
        
        public System.Threading.Tasks.Task<int> f2cAsync(int fahreneheit) {
            return base.Channel.f2cAsync(fahreneheit);
        }
    }
}
